### ISSUE TITLE
YAML config files

### ISSUE THREAD

**Issue by dan-blanchard** [EducationalTestingService/skll#209]
This will have to wait until after the 1.0 release, but while I was updating some documentation today it dawned on me that we're doing a lot of weird things with lists of parameters for learners that suggest a better format for the config files.  For example, the `fixed_parameters` list needs to be as long as the `learners` list, even if you only want to set parameters for one learner.  If we used YAML for config files, we could have a more sensible `learners` list that was a list of dictionaries.

``` yaml
experiment_name: Titanic_Evaluate_Tuned
task: evaluate

input:
  train_directory: train
  test_directory: dev
  featuresets:
    - [family.csv, misc.csv, socioeconomic.csv, vitals.csv]
    - [socioeconomic.csv, vitals.csv]
  id_col: PassengerId
  label_col: Survived

learners:
  DecisionTreeClassifier:
    fixed_parameters: {random_state: 123456789}
    parameter_grid:
      - max_features: [auto, null]
  MultinomialNB: null
  RandomForestClassifier:
    fixed_parameters: {random_state: 123456789}
  SVC:
    parameter_grid:
      - C: [0.01, 0.1, 1.0, 10.0, 100.0]
        gamma: [0.01, 0.1, 1.0, 10.0, 100.0]

tuning:
  grid_search: true
  objective: accuracy

output:
  log: output
  models: output
  predictions: output
  result: output
```

You'll notice that I also eliminated the `General` section, because YAML doesn't require everything to be in a section.  It's debatable what other things we might want to pull out of their sections and put at the global level too.

If we load that example config up with PyYAML, we get the following Python data structure:

``` python
{'experiment_name': 'Titanic_Evaluate_Tuned',
 'input': {'featuresets': [['family.csv',
                            'misc.csv',
                            'socioeconomic.csv',
                            'vitals.csv'],
                           ['socioeconomic.csv', 'vitals.csv']],
           'id_col': 'PassengerId',
           'label_col': 'Survived',
           'test_directory': 'dev',
           'train_directory': 'train'},
 'learners': {'DecisionTreeClassifier': {'fixed_parameters': {'random_state': 123456789},
                                         'parameter_grid': [{'max_features': ['auto',
                                                                              None]}]},
              'MultinomialNB': None,
              'RandomForestClassifier': {'fixed_parameters': {'random_state': 123456789}},
              'SVC': {'parameter_grid': [{'C': [0.01,
                                                0.1,
                                                1.0,
                                                10.0,
                                                100.0],
                                          'gamma': [0.01,
                                                    0.1,
                                                    1.0,
                                                    10.0,
                                                    100.0]}]}},
 'output': {'log': 'output',
            'models': 'output',
            'predictions': 'output',
            'result': 'output'},
 'task': 'evaluate',
 'tuning': {'grid_search': True, 'objective': 'accuracy'}}
```
